- name: clone latest ffmpeg
  git: repo=git://github.com/FFmpeg/FFmpeg.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/ffmpeg

- name: compile ffmpeg
  environment: "{{ ffmpeg_env|default({}) }}"
  shell: 'cd {{ ffmpeg_source_dir }}/ffmpeg; {{ item }} creates={{ ffmpeg_bin_dir }}/ffmpeg'
  with_items:
    - git checkout -b n4.0.2
    - PKG_CONFIG_PATH="{{ ffmpeg_build }}/lib/pkgconfig" ./configure --prefix={{ ffmpeg_build }} {{ ffmpeg_flags }}
    - make
    - make install

- name: reset ffmpeg
  shell: 'cd {{ ffmpeg_source_dir }}/ffmpeg; {{ item }} removes={{ ffmpeg_source_dir }}/ffmpeg/ffmpeg'
  with_items:
    - git checkout master
    - git branch -d n4.0.2
    - make distclean
