- name: clone latest opus
  git: repo=git://github.com/xiph/opus.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/opus

- name: compile libopus
  shell: 'cd {{ ffmpeg_source_dir }}/opus; {{ item }} creates={{ ffmpeg_build }}/lib/libopus.a'
  with_items:
    - git checkout -b v1.3-rc
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --disable-shared
    - make
    - make install

- name: reset libopus
  shell: 'cd {{ ffmpeg_source_dir }}/opus; {{ item }} removes={{ ffmpeg_source_dir }}/opus/libopus.la'
  with_items:
    - git checkout master
    - git branch -d v1.3-rc
    - make distclean
