- name: clone latest x264
  git: repo=git://git.videolan.org/x264.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/x264

- name: compile x264
  environment: "{{ ffmpeg_env|default({}) }}"
  shell: 'cd {{ ffmpeg_source_dir }}/x264; {{ item }} creates={{ ffmpeg_bin_dir }}/x264'
  with_items:
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }} --enable-static --enable-pic
    - make
    - make install

- name: reset x264
  shell: 'cd {{ ffmpeg_source_dir }}/x264; {{ item }} removes={{ ffmpeg_source_dir}}/x264/x264'
  with_items:
    - make distclean

