- name: clone latest yasm
  git: repo=git://github.com/yasm/yasm.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/yasm

- name: compile yasm
  shell: 'cd {{ ffmpeg_source_dir }}/yasm; {{ item }} creates={{ ffmpeg_bin_dir }}/yasm'
  with_items:
    - git checkout -b v1.3.0
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }}
    - make
    - make install

- name: reset yasm
  shell: 'cd {{ ffmpeg_source_dir }}/yasm; {{ item }} removes={{ ffmpeg_source_dir }}/yasm/Makefile'
  with_items:
    - git checkout master
    - git branch -d v1.3.0
    - make distclean
