- name: Download ipfs-updater
  get_url:
    url: https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
    dest: /tmp/ipfs-update.tar.gz
    checksum: sha256:d6430f832bcdc1aff16351f8ff894143d2e072d7dd3cc31f1ac6592e0528cca3
    mode: 0777

- name: "Extracting ipfs-updater to {{ home_dir }}"
  unarchive:
    remote_src: true
    src: /tmp/ipfs-update.tar.gz
    dest: "{{ home_dir }}"
  ignore_errors: true

- name: Running ipfs-upgrade v0.4.17
  command: "{{ home_dir }}/ipfs-update/ipfs-update install v0.4.17"
  args:
    creates: /usr/local/bin/ipfs
